name: marker_point
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.0
  go_router: ^8.0.5
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.5.0+1
  http: ^1.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  location: ^4.4.0
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  hydrated_bloc: ^9.1.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

